# Generated by Django 5.2.4 on 2025-08-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaireview',
            old_name='comment',
            new_name='comment_count',
        ),
        migrations.RemoveField(
            model_name='chaivariety',
            name='type',
        ),
        migrations.RemoveField(
            model_name='store',
            name='chai_variety',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_name',
        ),
        migrations.RemoveField(
            model_name='store',
            name='user',
        ),
        migrations.AddField(
            model_name='chaivariety',
            name='chai_type',
            field=models.CharField(choices=[('ML', 'Masala'), ('GR', 'Ginger'), ('KL', 'Kiwi'), ('PL', 'Plain'), ('EL', 'Elaichi')], default='ML', max_length=2),
        ),
        migrations.AddField(
            model_name='store',
            name='chai_varieties',
            field=models.ManyToManyField(related_name='stores', to='chai.chaivariety'),
        ),
        migrations.AlterField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
