# Generated by Django 5.2.3 on 2025-12-04 05:56

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0005_rename_comment_chaireview_comment_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chaicertificate',
            options={'ordering': ['-date_issued']},
        ),
        migrations.AlterModelOptions(
            name='chaireview',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='chaivariety',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='chaicertificate',
            name='certificate_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='chaicertificate',
            name='date_issued',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chaireview',
            name='date_added',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chaireview',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
        migrations.AlterField(
            model_name='chaivariety',
            name='chai_type',
            field=models.CharField(choices=[('ML', 'Masala'), ('GR', 'Ginger'), ('KL', 'Kiwi'), ('PL', 'Plain'), ('EL', 'Elaichi')], db_index=True, default='ML', max_length=2),
        ),
        migrations.AlterField(
            model_name='chaivariety',
            name='date_added',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='store',
            name='date_added',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='chaicertificate',
            index=models.Index(fields=['user', '-date_issued'], name='chai_chaice_user_id_274662_idx'),
        ),
        migrations.AddIndex(
            model_name='chaireview',
            index=models.Index(fields=['chai_variety', '-date_added'], name='chai_chaire_chai_va_8ff365_idx'),
        ),
        migrations.AddIndex(
            model_name='chaireview',
            index=models.Index(fields=['user', '-date_added'], name='chai_chaire_user_id_f720aa_idx'),
        ),
        migrations.AddIndex(
            model_name='chaivariety',
            index=models.Index(fields=['chai_type', '-date_added'], name='chai_chaiva_chai_ty_2d6155_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['-date_added'], name='chai_store_date_ad_52cab5_idx'),
        ),
    ]
