# Generated by Django 5.2.3 on 2025-12-04 05:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0006_alter_chaicertificate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('chai_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='chai.chaivariety')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_chais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
                'indexes': [models.Index(fields=['user', '-date_added'], name='chai_favori_user_id_edf67b_idx')],
                'unique_together': {('user', 'chai_variety')},
            },
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('date_added', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_helpful', models.IntegerField(default=0)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='chai.chaireview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
                'indexes': [models.Index(fields=['review', '-date_added'], name='chai_review_review__a5da01_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='chai.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
                'indexes': [models.Index(fields=['store', '-date_added'], name='chai_storer_store_i_3880d9_idx'), models.Index(fields=['user', '-date_added'], name='chai_storer_user_id_d27510_idx')],
                'unique_together': {('store', 'user')},
            },
        ),
    ]
